display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
          tags:
            previous: '‹ السابقة'
            next: 'التالية ›'
            first: '« الأولى'
            last: 'الأخيرة »'
      fields:
        created:
          label: الإنشاء
        filesize:
          label: 'حجم الملف'
        status:
          label: الحالة
      filters:
        filename:
          expose:
            label: 'اسم الملف'
